// Plant a minimal runtime-profile.yml in a project root.
// Tier is overlay: none. No backend or commands — the project fills those.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { resolveAddressing } from './addressing.mjs';
import { ALIASES, ENGINES } from './engines.mjs';
import { formatValidateReport, parseProfile } from './profile.mjs';

export const PROFILE_RELPATH = path.join('.agents', 'runtime-profile.yml');

const SLUG = /^[a-z][a-z0-9_-]*$/;
const DNS_LABEL = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

export function slugFromName(name) {
  let s = String(name)
    .toLowerCase()
    .replaceAll(/[^a-z0-9_-]+/g, '-')
    .replaceAll(/^-+|-+$/g, '');
  s = s.replace(/^[^a-z]+/, '');
  return s.length > 0 && SLUG.test(s) ? s : null;
}

export function parseCsv(value) {
  if (value == null || value === '') return [];
  return String(value)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

export function resolveEnginesFlag(names) {
  const out = [];
  for (const name of names) {
    const canon = ALIASES[name] ?? name;
    if (!(canon in ENGINES)) {
      throw new Error(`unknown engine "${name}" — supported: ${Object.keys(ENGINES).join(', ')}`);
    }
    if (!out.includes(canon)) out.push(canon);
  }
  return out;
}

export function resolveServicesFlag(names) {
  for (const name of names) {
    if (!DNS_LABEL.test(name)) {
      throw new Error(`services key must be a DNS label — ${JSON.stringify(name)}`);
    }
  }
  return names;
}

export function parseInitArgs(args) {
  let root;
  const opts = { slug: null, engines: [], services: [], force: false };
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === '--force') {
      opts.force = true;
      continue;
    }
    if (arg === '--slug' || arg === '--engines' || arg === '--services') {
      const value = args[i + 1];
      if (value == null || value.startsWith('--')) {
        throw new Error(`${arg} needs a value.`);
      }
      i += 1;
      if (arg === '--slug') opts.slug = value;
      if (arg === '--engines') opts.engines = parseCsv(value);
      if (arg === '--services') opts.services = parseCsv(value);
      continue;
    }
    if (arg.startsWith('--')) {
      throw new Error(`unknown option "${arg}"`);
    }
    if (root != null) {
      throw new Error(`only one project root — ${JSON.stringify(arg)}`);
    }
    root = arg;
  }
  return { root: root ?? '.', ...opts };
}

export function renderInitYaml({ slug, engines = [], services = [] }) {
  if (!SLUG.test(slug)) {
    throw new Error(`project.slug is missing or malformed — ${JSON.stringify(slug)}`);
  }
  const canonEngines = resolveEnginesFlag(engines);
  const canonServices = resolveServicesFlag(services);
  const lines = [
    '# generated by de-novo skills init — edit values for this project.',
    'version: 1',
    '',
    'project:',
    `  slug: ${slug}`,
    '',
    'addressing:',
    '  # tld omitted — this Grove checkout\'s infra/addressing.yml',
    '  # (addressing.local.yml in that directory overrides, gitignored).',
    '  # Pin a domain in this project: tld: local.example.com',
    '  scheme:',
    '    shared: "{service}.{project}.{tld}"',
    '',
    'runtime:',
    '  single_stack: true',
    '  writers: 1',
    '',
  ];
  if (canonServices.length > 0) {
    lines.push('services:');
    for (const name of canonServices) {
      lines.push(`  ${name}: {}`);
    }
    lines.push('');
  }
  lines.push('overlay: none', '', 'data:', '  infra: machine');
  if (canonEngines.length === 0) {
    lines.push('  engines: {}');
  } else {
    lines.push('  engines:');
    for (const name of canonEngines) {
      lines.push(`    ${name}: true`);
    }
  }
  lines.push('  forbid_direct_db_writes: true', '');
  return lines.join('\n');
}

export function runInit(args, cwd = process.cwd()) {
  const opts = parseInitArgs(args);
  const root = path.resolve(cwd, opts.root);
  const slug = opts.slug ?? slugFromName(path.basename(root));
  if (!slug) {
    throw new Error(
      `cannot derive a slug from directory name (${path.basename(root)}). pass --slug.`
    );
  }
  const yamlText = renderInitYaml({
    slug,
    engines: opts.engines,
    services: opts.services,
  });
  const file = path.join(root, PROFILE_RELPATH);
  if (existsSync(file) && !opts.force) {
    throw new Error(`already exists: ${file}\npass --force to overwrite.`);
  }
  const profile = parseProfile(yamlText, file);
  const addressing = resolveAddressing(profile, { profilePath: file });
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, yamlText);
  const engineCount = Object.keys(profile.engines).length;
  const serviceCount = Object.keys(profile.services).length;
  console.log(`■ ${slug} — profile created`);
  console.log(`  file     1/1: ${file}`);
  console.log(`  apps     ${serviceCount} (services)`);
  console.log(`  engines  ${engineCount} (data.engines)`);
  console.log(formatValidateReport(profile, addressing));
  console.log('next: edit the profile, then de-novo skills validate and urls. Machine setup requires owner authorization; see the CLI checkout infra/README.md.');
  return 0;
}
